default: &default
  prepared_statements: false
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['PGHOST'] || 'localhost' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PGUSER'] || 'postgres' %>
  password: <%= ENV['PGPASSWORD'] %>
  timeout: 5000

development:
  <<: *default
  database: ekis_development

test:
  <<: *default
  database: ekis_test

production:
  <<: *default
  database: ekis
