AllCops:
  Include:
  - '**/Guardfile'
  - '**/Rakefile'
  - '**/Gemfile'
  - '**/config.ru'
  - lib/**/*
  Exclude:
  - 'bin/**/*'
  - 'db/**/*'
#  - 'config/**/*'

  TargetRubyVersion: 2.3

Rails/UnknownEnv:
  Environments:
  - production
  - development
  - test
  - playing
  - staging

Rails:
  Enabled: true

AbcSize:
  Enabled: false

ClassLength:
  Enabled: false

Documentation:
  Enabled: false

LineLength:
  Enabled: false

LambdaCall:
  Enabled: false

MethodLength:
  Max: 15

RaiseArgs:
  Enabled: false

HasAndBelongsToMany:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

Style/MixinGrouping:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

# TODO: Enable all these cops once we go live with org
Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/RandomWithOffset:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Lint/UriEscapeUnescape:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Security/Open:
  Enabled: false

Rails/ActiveRecordAliases:
  Enabled: false
